### ISSUE TITLE
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdeadbaad

### ISSUE THREAD

**Issue by ray0807** [alexandruc/android-bpg#6]
Hi,I need your help，I'm not good at clang, so I don't know what to do。
1.I test this library in my project, The vast majority of mobile phones can  work. but  I do monkey test on someone, it reports Native Crash. 
2.I used [https://github.com/nostra13/Android-Universal-Image-Loader](url) and  Customize my own Downloader（using bpg decoder [https://github.com/nostra13/Android-Universal-Image-Loader/blob/master/sample/src/main/java/com/nostra13/universalimageloader/sample/ext/OkHttpImageDownloader.java](url) )
3.I consulted a lot of information and test ，the crash line is this method(decoder.c-->bmp_save_to_buffer()-->free(rgb_line)  )  , I find this  [https://groups.google.com/forum/#!topic/android-ndk/jQg6DM6-D6o](url) 
![image](https://cloud.githubusercontent.com/assets/7233544/24148353/618a0c6a-0e79-11e7-81b5-7ebb6d1a40fb.png)

please help me , I don't know how to solve.

Monkey log:
// CRASH: com.xmtj.mkz (pid 24884)
// Short Msg: Native crash
// Long Msg: Native crash: Segmentation fault
// Build Label: SMARTISAN/msm8916_32:5.1.1/LMY47V/59:user/release-keys
// Build Changelist: 59
// Build Time: 1484324676000
// *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
// Build fingerprint: 'SMARTISAN/msm8916_32:5.1.1/LMY47V/59:user/release-keys'
// Revision: '0'
// ABI: 'arm'
// pid: 24884, tid: 25593, name: uil-pool-1-thre  >>> com.xmtj.mkz <<<
// signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdeadbaad
// Abort message: 'invalid address or address of corrupt block 0xb83b4cb0 passed to dlfree'
//     r0 00000000  r1 b6e89dec  r2 deadbaad  r3 00000000
//     r4 b83b4cb0  r5 b6e8b0f8  r6 00000000  r7 00000200
//     r8 00000db5  r9 98794838  sl 00001de4  fp 00000db5
//     ip 00000000  sp 98794780  lr b6e5bdaf  pc b6e5bdb0  cpsr 680f0030
// 
// backtrace:
//     #00 pc 00028db0  /system/lib/libc.so (dlfree+1239)
//     #01 pc 0000f2b3  /system/lib/libc.so (free+10)
//     #02 pc 00005a99  /data/app/com.xmtj.mkz-1/lib/arm/libbpg_decoder.so (decode_buffer+412)
//     #03 pc 00005de5  /data/app/com.xmtj.mkz-1/lib/arm/libbpg_decoder.so (Java_com_xmtj_bpgdecoder_DecoderWrapper_decodeBuffer+108)
//     #04 pc 0066c7a5  /data/dalvik-cache/arm/data@app@com.xmtj.mkz-1@base.apk@classes.dex
// 
    // Injection Failed
** Monkey aborted due to error.

**Comment by alexandruc** [comment]
I have tested on a few Nexus devices and the emulator and didn't reproduce.
Is this issue reproduced with some specific image? If so, please attach it so I can test.

**Comment by ray0807** [comment]
This happens only occasionally，In a number of old models(坚果手机YQ601...) to extract multiple images at once, this problem may arise,The problem seems to be related to memory usage.
